### ISSUE TITLE
Divide by zero occurring when division is performed with a result of a multiplication

### ISSUE THREAD

**Issue by Himeshi** [fp-analysis/klee#78] opened 2018-02-16 13:53 UTC
The following code produces a divide by zero error even with `--scaling` argument.

	int main() { int a = 3, b = 2, answer;

	klee_make_symbolic(&a, sizeof(a), "a");
	klee_make_symbolic(&b, sizeof(b), "b");

	klee_track_error(&a, "error_a");
	klee_track_error(&b, "error_b");

	answer = a + (b * b);

	klee_bound_error(answer, "answer", 1.3);
	return 0; }

The expression for `answer` however contains the scaling expression.

**Comment by domainexpert** [comment] 2018-02-18 12:28
@Himeshi I failed to observe this. I tried the following more complete version:
```
/*
 * This example triggers division by zero when run with scaling.
 *
 * Copyright 2018 National University of Singapore
 *
 * by Himeshi De Silva <himeshidslv@gmail.com>
 */
#include <klee/klee.h>

int main() {
  int a = 3, b = 2, answer;

  klee_make_symbolic(&a, sizeof(a), "a");
  klee_make_symbolic(&b, sizeof(b), "b");

  klee_track_error(&a, "error_a");
  klee_track_error(&b, "error_b");

  answer = a + (b * b);

  klee_bound_error(answer, "answer", 1.3);
  return 0;
}
```
What were the exact options you ran KLEE with?

**Comment by Himeshi** [comment] 2018-02-18 14:23
klee --write-kqueries --precision --scaling add_test.bc

**Comment by domainexpert** [comment] 2018-02-23 04:09
@Himeshi I am still not able to observe the issue.

**Comment by Himeshi** [comment] 2018-02-26 09:17
It should be a divide, not an add which computes the answer. Corrected code below.

```
/*
 * This example triggers division by zero when run with scaling.
 *
 * Copyright 2018 National University of Singapore
 *
 * by Himeshi De Silva <himeshidslv@gmail.com>
 */
#include <klee/klee.h>

int main() {
  int a = 3, b = 2, answer;

  klee_make_symbolic(&a, sizeof(a), "a");
  klee_make_symbolic(&b, sizeof(b), "b");

  klee_track_error(&a, "error_a");
  klee_track_error(&b, "error_b");

  answer = a  /  (b * b);

  klee_bound_error(answer, "answer", 1.3);
  return 0;
}
```

**Comment by domainexpert** [comment] 2018-03-03 04:12
@Himeshi Ok confirmed. I'll work on this. This is my output:
```$ $HOME/software/fp-analysis-klee/build/bin/klee --write-kqueries --precision --scaling division.bc
KLEE: output directory is "/home/andrew/software/fp-examples/basic/klee-out-0"
KLEE: Using STP solver backend
KLEE: ERROR: /home/andrew/software/fp-examples/basic/division.c:19: divide by zero
KLEE: NOTE: now ignoring this error at this location

KLEE: done: total instructions = 26
KLEE: done: completed paths = 2
KLEE: done: generated tests = 2
```

**Comment by domainexpert** [comment] 2018-03-03 11:14
@Himeshi This seems to not actually be a problem. This is because indeed division by zero should occur because b is symbolic (thus there is a possibility that b times b = 0). Now, the purpose of scaling is to multiply the numerator by a constant so that the result of division does not get rounded to 0. The scaling cannot prevent division by zero when, as in this case, the divisor is a symbolic value that can be assigned 0.

I will let you close this issue if you agree.

**Closed as completed** 2018-03-04 01:47 UTC
